name: GitHub Action For Running Tosca
run-name: ${{ github.actor }} is Running Tosca Tests via the AOS API! 🚀
on: [push]
jobs:
  Execute-Tosca-Tests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check if the TestEvents.json file exists in the repo
        shell: pwsh
        run: Test-Path TestEvents.json | Should -Be $true
      - name: Run Tosca Tests on Andrew's VM
        shell: pwsh
        run: |  
          .\tosca_execution_client.ps1 -toscaServerUrl "https://6cb1-77-248-179-205.ngrok-free.app" -projectName "Tricentis_Main" -eventsConfigFilePath "TestEvents.json" -clientId "u2pFVfQPnEC5lbUgEiEc4w" -clientSecret "p0vBGIfkY0u6IIC3TwMnhg3zBOhM8Bnk6RyvrUO2ZI3Q" -creator "Github-ToscaExecutionClient" -debug "true" -executionEnvironment "Dex" -pollingInterval 10
      - name: Process JUnit Results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/results/*results.xml'
          require_tests: true
